In [1]:
import pandas as pd
import numpy as np

In [5]:
## onset data ## time entering a page per person
# keep column "time"
# turn "time" into array and reshape


folder_path = "/Users/apple/Desktop/deep_eye/dataset/onset_time_A/"
onset = []
for i in range(1,31):
    if i <= 9:
        path_csv = folder_path + "A0" + str(i) + ".csv"
        df = pd.read_csv(path_csv)
        onset = np.concatenate((onset, df.iloc[:47]['time']))
        #read_file.to_csv (path_csv, index = None, header=True) 
    else:
        path_csv = folder_path + "A" + str(i) + ".csv"
        df = pd.read_csv(path_csv)
        onset = np.concatenate((onset, df.iloc[:47]['time']))

print("onset len: 30*47=", len(onset))

onset_array = onset.reshape(30,47)
print(onset_array.shape)

##################################################################
## response data OK ##
# keep column "time"
# turn "time" into array and reshape

folder_path = "/Users/apple/Desktop/deep_eye/dataset/resp_time_A/"
resp = []
for i in range(1,31):
    if i <= 9:
        path_csv = folder_path + "A0" + str(i) + ".csv"
        df = pd.read_csv(path_csv)
        resp = np.concatenate((resp, df.iloc[:47]['time']))
        #read_file.to_csv (path_csv, index = None, header=True) 
    else:
        path_csv = folder_path + "A" + str(i) + ".csv"
        df = pd.read_csv(path_csv)
        resp = np.concatenate((resp, df.iloc[:47]['time']))

print("resp len: 30*47=", len(resp))

resp_array = resp.reshape(30,47)
print(resp_array.shape)

onset len: 30*47= 1410
(30, 47)
resp len: 30*47= 1410
(30, 47)

In [51]:
# 先用第一個人測試
df = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/raw_A/A01.csv")
df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
df_col.columns = ['start_time', 'x', 'y', 'duration']

# form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
# QCP_combine = pd.DataFrame(columns=['start_time', 'x', 'y', 'duration']) # empty df
# QCP = []
# QCP_duration = []
p=1
q=1
# for q in range(1,48):
if int(resp_array[p-1][q-1]) == 0:
    df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
else:
    df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
## df_cor = df_time[(df_time['x'] >= x_cor.iloc[q-1].min()) & (df_time['x'] <= x_cor.iloc[q-1].max()) & (df_time['y'] >= y_cor.iloc[q-1].min()) & (df_time['y'] <= y_cor.iloc[q-1].max())] # xy in AOI
df_time = df_time[(df_time['duration']>= 100)] # duration >= 100
df_time

    start_time       x       y  duration
3          749   389.2   252.3       138
5         1056   778.7   256.5       112
6         1208   962.6   260.6       116
8         1518   315.5   357.7       204
9         1786   859.0   572.1       184
12        2353   997.1   553.2       166
13        2565   811.8   554.5       307
14        2917   733.4   565.1       134
15        3090   904.9   544.6       107
16        3234  1000.6   539.8       122
17        3417   810.1   236.7       117
18        3587   489.8   260.0       174
20        3932   765.8   251.2       187
23        4491   883.3   245.1       189
26        5008   302.4   380.8       146
27        5179   438.4   380.6       194
28        5444   892.5   563.0       150
29        5632  1004.5   566.3       111
30        6065  1004.3   250.6       131
32        6406   289.9   368.1       210
33        6669   300.5   274.2       284
34        6981   477.1   258.3       141
35        7388   931.0   604.8       258
36        7676   850.6   640.8       146
38        7957   918.9   622.4       180
39        8182   964.1   497.0       218
42        8780   963.6   230.6       125
43        8956   769.6   244.3       160
46        9573   817.6   528.2       157
48        9912   817.6   506.2       201
49       10476  1749.7  2167.0       345
50       11079   955.3   522.1       220
52       11556   862.3   574.9       265
53       11860   937.6   696.8       206
54       12112   949.6   513.4       106
55       12245   770.2   535.1       377
57       12937  1672.8  2213.1       473
58       13627   676.5   490.9       108
59       13784   833.9   553.3       360

In [2]:
# AOI range x & y data
x_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_x_2ndline.csv")
y_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_y_2ndline.csv")

word_per_page_count = x_raw.iloc[-1, 1:]

x_AOI = x_raw.iloc[:-1, 1:]
y_AOI = y_raw.iloc[:-1, 1:]

x_AOI_range = []
for i in range(x_AOI.shape[1]):
    xpage = x_AOI.iloc[:,i]
    x_AOI_range.append(list(xpage[xpage.notna()]))

y_AOI_range = []
for i in range(y_AOI.shape[1]):
    ypage = y_AOI.iloc[:,i]
    y_AOI_range.append(list(ypage[ypage.notna()]))

In [3]:
x_AOI_range

[[117.0,
  190.0,
  191.0,
  250.0,
  251.0,
  365.0,
  366.0,
  425.0,
  426.0,
  475.0,
  476.0,
  540.0,
  541.0,
  595.0,
  596.0,
  652.0,
  653.0,
  710.0,
  711.0,
  775.0,
  776.0,
  833.0,
  834.0,
  950.0,
  1000.0,
  1141.0,
  117.0,
  190.0,
  191.0,
  250.0,
  251.0,
  365.0,
  366.0,
  435.0,
  755.0,
  888.0,
  889.0,
  978.0,
  979.0,
  1053.0,
  755.0,
  888.0,
  889.0,
  978.0,
  979.0,
  1053.0,
  755.0,
  888.0,
  889.0,
  978.0,
  979.0,
  1053.0],
 [155.0,
  288.0,
  289.0,
  401.0,
  402.0,
  513.0,
  514.0,
  629.0,
  630.0,
  745.0,
  746.0,
  800.0,
  845.0,
  913.0,
  914.0,
  968.0,
  969.0,
  1097.0,
  155.0,
  227.0,
  228.0,
  351.0,
  525.0,
  675.0,
  525.0,
  655.0,
  656.0,
  713.0,
  714.0,
  775.0,
  815.0,
  882.0,
  883.0,
  938.0,
  939.0,
  1050.0,
  1051.0,
  1110.0,
  1111.0,
  1184.0,
  525.0,
  655.0,
  656.0,
  713.0,
  714.0,
  775.0,
  815.0,
  882.0,
  883.0,
  938.0,
  939.0,
  1050.0,
  1051.0,
  1110.0,
  1111.0,
  1184.0],
 [109.0,
  190.0,
  191.0,
  304.0,
  305.0,
  428.0,
  470.0,
  587.0,
  588.0,
  705.0,
  706.0,
  818.0,
  819.0,
  934.0,
  935.0,
  1120.0,
  109.0,
  247.0,
  248.0,
  307.0,
  308.0,
  360.0,
  361.0,
  422.0,
  423.0,
  475.0,
  476.0,
  532.0,
  533.0,
  591.0,
  592.0,
  655.0,
  748.0,
  892.0,
  748.0,
  892.0,
  748.0,
  871.0,
  872.0,
  936.0],
 [114.0,
  250.0,
  251.0,
  370.0,
  410.0,
  475.0,
  476.0,
  593.0,
  594.0,
  645.0,
  646.0,
  761.0,
  762.0,
  874.0,
  875.0,
  1046.0,
  1047.0,
  1121.0,
  114.0,
  190.0,
  191.0,
  303.0,
  304.0,
  418.0,
  419.0,
  542.0,
  740.0,
  860.0,
  861.0,
  1000.0,
  740.0,
  860.0,
  861.0,
  1000.0,
  740.0,
  975.0,
  976.0,
  1104.0],
 [112.0,
  187.0,
  188.0,
  303.0,
  304.0,
  419.0,
  420.0,
  535.0,
  536.0,
  590.0,
  591.0,
  705.0,
  706.0,
  825.0,
  867.0,
  930.0,
  931.0,
  1046.0,
  112.0,
  192.0,
  193.0,
  250.0,
  251.0,
  304.0,
  305.0,
  418.0,
  419.0,
  534.0,
  535.0,
  590.0,
  591.0,
  649.0,
  650.0,
  704.0,
  705.0,
  757.0,
  758.0,
  818.0,
  819.0,
  940.0,
  700.0,
  835.0,
  836.0,
  975.0,
  700.0,
  777.0,
  778.0,
  930.0,
  700.0,
  777.0,
  778.0,
  833.0,
  834.0,
  892.0,
  893.0,
  1005.0,
  1006.0,
  1064.0,
  1065.0,
  1138.0],
 [87.0,
  164.0,
  165.0,
  227.0,
  228.0,
  278.0,
  279.0,
  394.0,
  395.0,
  505.0,
  506.0,
  564.0,
  565.0,
  679.0,
  680.0,
  792.0,
  793.0,
  860.0,
  900.0,
  960.0,
  961.0,
  1019.0,
  1020.0,
  1076.0,
  87.0,
  163.0,
  164.0,
  340.0,
  341.0,
  450.0,
  451.0,
  515.0,
  560.0,
  622.0,
  623.0,
  680.0,
  681.0,
  734.0,
  735.0,
  850.0,
  851.0,
  905.0,
  906.0,
  964.0,
  965.0,
  1085.0,
  750.0,
  826.0,
  827.0,
  885.0,
  886.0,
  942.0,
  943.0,
  1100.0,
  750.0,
  826.0,
  827.0,
  885.0,
  886.0,
  942.0,
  943.0,
  1100.0,
  750.0,
  826.0,
  827.0,
  885.0,
  886.0,
  999.0,
  1000.0,
  1134.0],
 [221.0,
  358.0,
  359.0,
  414.0,
  415.0,
  530.0,
  531.0,
  583.0,
  584.0,
  643.0,
  644.0,
  753.0,
  754.0,
  813.0,
  814.0,
  990.0,
  740.0,
  802.0,
  803.0,
  885.0,
  740.0,
  802.0,
  803.0,
  885.0,
  740.0,
  854.0,
  855.0,
  934.0],
 [109.0,
  175.0,
  176.0,
  228.0,
  229.0,
  272.0,
  273.0,
  387.0,
  388.0,
  513.0,
  550.0,
  615.0,
  616.0,
  670.0,
  671.0,
  712.0,
  713.0,
  827.0,
  828.0,
  953.0,
  989.0,
  1049.0,
  1050.0,
  1103.0,
  109.0,
  185.0,
  220.0,
  271.0,
  272.0,
  326.0,
  327.0,
  383.0,
  384.0,
  501.0,
  502.0,
  556.0,
  557.0,
  669.0,
  670.0,
  783.0,
  784.0,
  898.0,
  899.0,
  1018.0,
  735.0,
  783.0,
  784.0,
  818.0,
  819.0,
  853.0,
  854.0,
  887.0,
  888.0,
  947.0,
  735.0,
  783.0,
  784.0,
  818.0,
  819.0,
  853.0,
  854.0,
  887.0,
  888.0,
  947.0,
  735.0,
  783.0,
  784.0,
  818.0,
  819.0,
  853.0,
  854.0,
  887.0,
  888.0,
  947.0],
 [106.0,
  187.0,
  188.0,
  302.0,
  303.0,
  415.0,
  416.0,
  470.0,
  471.0,
  530.0,
  531.0,
  584.0,
  585.0,
  643.0,
  644.0,
  711.0,
  745.0,
  815.0,
  816.0,
  869.0,
  870.0,
  926.0,
  927.0,
  982.0,
  983.0,
  1101.0,
  743.0,
  860.0,
  743.0,
  860.0,
  743.0,
  860.0],
 [94.0,
  175.0,
  176.0,
  346.0,
  347.0,
  461.0,
  462.0,
  518.0,
  519.0,
  574.0,
  575.0,
  685.0,
  686.0,
  745.0,
  746.0,
  799.0,
  800.0,
  869.0,
  905.0,
  1029.0,
  1030.0,
  1162.0,
  94.0,
  234.0,
  235.0,
  289.0,
  290.0,
  346.0,
  347.0,
  461.0,
  462.0,
  584.0,
  620.0,
  692.0,
  693.0,
  744.0,
  745.0,
  803.0,
  804.0,
  859.0,
  860.0,
  914.0,
  915.0,
  974.0,
  975.0,
  1096.0,
  612.0,
  749.0,
  750.0,
  900.0,
  612.0,
  749.0,
  750.0,
  900.0,
  612.0,
  693.0,
  694.0,
  746.0,
  747.0,
  863.0,
  864.0,
  918.0,
  919.0,
  1034.0,
  1035.0,
  1092.0,
  1093.0,
  1161.0],
 [112.0,
  190.0,
  191.0,
  305.0,
  306.0,
  419.0,
  420.0,
  601.0,
  639.0,
  705.0,
  706.0,
  762.0,
  763.0,
  818.0,
  819.0,
  931.0,
  932.0,
  1057.0,
  112.0,
  190.0,
  191.0,
  247.0,
  248.0,
  419.0,
  420.0,
  479.0,
  480.0,
  530.0,
  531.0,
  590.0,
  591.0,
  710.0,
  750.0,
  826.0,
  827.0,
  883.0,
  884.0,
  975.0,
  750.0,
  826.0,
  827.0,
  883.0,
  884.0,
  975.0,
  750.0,
  826.0,
  827.0,
  883.0,
  884.0,
  1000.0,
  1001.0,
  1054.0,
  1055.0,
  1130.0],
 [110.0,
  191.0,
  192.0,
  249.0,
  250.0,
  307.0,
  308.0,
  422.0,
  423.0,
  477.0,
  478.0,
  594.0,
  595.0,
  705.0,
  706.0,
  758.0,
  759.0,
  932.0,
  933.0,
  1059.0,
  110.0,
  248.0,
  249.0,
  364.0,
  365.0,
  420.0,
  421.0,
  474.0,
  475.0,
  591.0,
  592.0,
  714.0,
  757.0,
  827.0,
  828.0,
  885.0,
  886.0,
  1020.0,
  757.0,
  827.0,
  828.0,
  885.0,
  886.0,
  1020.0,
  757.0,
  827.0,
  828.0,
  885.0,
  886.0,
  1000.0,
  1001.0,
  1129.0],
 [110.0,
  189.0,
  190.0,
  367.0,
  368.0,
  477.0,
  478.0,
  592.0,
  593.0,
  646.0,
  647.0,
  772.0,
  807.0,
  934.0,
  935.0,
  990.0,
  991.0,
  1122.0,
  110.0,
  252.0,
  253.0,
  363.0,
  364.0,
  485.0,
  620.0,
  673.0,
  674.0,
  723.0,
  724.0,
  766.0,
  767.0,
  806.0,
  807.0,
  866.0,
  620.0,
  673.0,
  674.0,
  723.0,
  724.0,
  766.0,
  767.0,
  806.0,
  807.0,
  866.0,
  620.0,
  673.0,
  674.0,
  723.0,
  724.0,
  766.0,
  767.0,
  806.0,
  807.0,
  866.0],
 [110.0,
  190.0,
  191.0,
  307.0,
  308.0,
  364.0,
  365.0,
  479.0,
  480.0,
  589.0,
  590.0,
  772.0,
  805.0,
  875.0,
  876.0,
  935.0,
  936.0,
  1049.0,
  1050.0,
  1122.0,
  110.0,
  190.0,
  191.0,
  364.0,
  365.0,
  475.0,
  476.0,
  590.0,
  591.0,
  713.0,
  734.0,
  890.0,
  734.0,
  890.0,
  734.0,
  792.0,
  793.0,
  850.0,
  851.0,
  1035.0],
 [117.0,
  260.0,
  261.0,
  371.0,
  372.0,
  426.0,
  427.0,
  483.0,
  483.0,
  539.0,
  540.0,
  654.0,
  655.0,
  713.0,
  714.0,
  767.0,
  768.0,
  880.0,
  881.0,
  1000.0,
  1001.0,
  1064.0,
  1100.0,
  1241.0,
  117.0,
  260.0,
  261.0,
  385.0,
  415.0,
  483.0,
  518.0,
  576.0,
  612.0,
  662.0,
  663.0,
  774.0,
  775.0,
  953.0,
  591.0,
  663.0,
  664.0,
  720.0,
  721.0,
  836.0,
  837.0,
  881.0,
  882.0,
  991.0,
  992.0,
  1080.0,
  591.0,
  721.0,
  722.0,
  778.0,
  779.0,
  891.0,
  892.0,
  931.0,
  932.0,
  985.0,
  986.0,
  1029.0,
  1030.0,
  1141.0,
  1142.0,
  1216.0,
  591.0,
  644.0,
  645.0,
  678.0,
  679.0,
  713.0,
  714.0,
  748.0,
  749.0,
  820.0],
 [110.0,
  190.0,
  191.0,
  423.0,
  424.0,
  537.0,
  538.0,
  599.0,
  635.0,
  817.0,
  818.0,
  934.0,
  935.0,
  987.0,
  988.0,
  1116.0,
  110.0,
  406.0,
  407.0,
  466.0,
  738.0,
  801.0,
  802.0,
  880.0,
  738.0,
  801.0,
  802.0,
  936.0,
  738.0,
  801.0,
  802.0,
  880.0],
 [110.0,
  190.0,
  191.0,
  306.0,
  307.0,
  420.0,
  421.0,
  485.0,
  520.0,
  650.0,
  651.0,
  707.0,
  708.0,
  761.0,
  762.0,
  888.0,
  920.0,
  990.0,
  991.0,
  1124.0,
  110.0,
  190.0,
  191.0,
  248.0,
  249.0,
  305.0,
  306.0,
  377.0,
  407.0,
  536.0,
  537.0,
  591.0,
  592.0,
  646.0,
  647.0,
  705.0,
  706.0,
  848.0,
  750.0,
  886.0,
  887.0,
  1030.0,
  750.0,
  886.0,
  887.0,
  1030.0,
  750.0,
  886.0,
  887.0,
  999.0,
  1000.0,
  1130.0],
 [120.0,
  190.0,
  191.0,
  308.0,
  309.0,
  364.0,
  365.0,
  417.0,
  418.0,
  543.0,
  580.0,
  704.0,
  705.0,
  819.0,
  820.0,
  1047.0,
  1048.0,
  1122.0,
  120.0,
  363.0,
  364.0,
  536.0,
  537.0,
  655.0,
  696.0,
  818.0,
  819.0,
  926.0,
  927.0,
  990.0,
  991.0,
  1122.0,
  120.0,
  250.0,
  251.0,
  373.0,
  631.0,
  692.0,
  693.0,
  923.0,
  924.0,
  980.0,
  981.0,
  1031.0,
  631.0,
  695.0,
  696.0,
  830.0,
  631.0,
  692.0,
  693.0,
  923.0,
  924.0,
  980.0,
  981.0,
  1031.0,
  631.0,
  695.0,
  696.0,
  830.0,
  631.0,
  692.0,
  693.0,
  752.0,
  753.0,
  807.0,
  808.0,
  860.0,
  861.0,
  980.0,
  981.0,
  1111.0],
 [102.0,
  184.0,
  185.0,
  293.0,
  294.0,
  353.0,
  354.0,
  409.0,
  410.0,
  466.0,
  467.0,
  522.0,
  523.0,
  579.0,
  580.0,
  752.0,
  753.0,
  868.0,
  869.0,
  929.0,
  970.0,
  1035.0,
  1036.0,
  1167.0,
  102.0,
  238.0,
  239.0,
  363.0,
  742.0,
  861.0,
  862.0,
  1003.0,
  742.0,
  861.0,
  862.0,
  1003.0,
  742.0,
  973.0,
  974.0,
  1107.0],
 [150.0,
  231.0,
  232.0,
  289.0,
  290.0,
  404.0,
  405.0,
  458.0,
  459.0,
  572.0,
  573.0,
  697.0,
  733.0,
  799.0,
  800.0,
  843.0,
  844.0,
  955.0,
  956.0,
  1085.0,
  150.0,
  230.0,
  231.0,
  272.0,
  273.0,
  326.0,
  327.0,
  370.0,
  371.0,
  481.0,
  482.0,
  538.0,
  539.0,
  597.0,
  598.0,
  717.0,
  830.0,
  988.0,
  830.0,
  988.0,
  830.0,
  952.0,
  953.0,
  1082.0],
 [115.0,
  251.0,
  252.0,
  309.0,
  310.0,
  479.0,
  480.0,
  536.0,
  537.0,
  595.0,
  596.0,
  751.0,
  752.0,
  831.0,
  860.0,
  991.0,
  992.0,
  1121.0,
  115.0,
  262.0,
  294.0,
  364.0,
  365.0,
  418.0,
  419.0,
  590.0,
  591.0,
  657.0,
  689.0,
  802.0,
  689.0,
  854.0,
  689.0,
  829.0,
  830.0,
  887.0,
  888.0,
  1020.0],
 [110.0,
  308.0,
  309.0,
  364.0,
  365.0,
  474.0,
  475.0,
  590.0,
  591.0,
  648.0,
  649.0,
  774.0,
  808.0,
  879.0,
  880.0,
  932.0,
  933.0,
  989.0,
  990.0,
  1115.0,
  110.0,
  247.0,
  248.0,
  359.0,
  360.0,
  420.0,
  421.0,
  478.0,
  479.0,
  533.0,
  534.0,
  588.0,
  589.0,
  647.0,
  648.0,
  703.0,
  704.0,
  830.0,
  750.0,
  811.0,
  812.0,
  865.0,
  866.0,
  955.0,
  750.0,
  811.0,
  812.0,
  865.0,
  866.0,
  955.0,
  750.0,
  811.0,
  828.0,
  881.0,
  882.0,
  994.0,
  995.0,
  1074.0],
 [110.0,
  190.0,
  191.0,
  305.0,
  306.0,
  428.0,
  470.0,
  588.0,
  589.0,
  706.0,
  707.0,
  817.0,
  818.0,
  934.0,
  935.0,
  1121.0,
  110.0,
  247.0,
  248.0,
  307.0,
  308.0,
  363.0,
  364.0,
  419.0,
  420.0,
  477.0,
  478.0,
  535.0,
  536.0,
  589.0,
  590.0,
  651.0,
  739.0,
  888.0,
  739.0,
  888.0,
  739.0,
  863.0,
  864.0,
  928.0],
 [104.0,
  245.0,
  246.0,
  358.0,
  359.0,
  413.0,
  414.0,
  469.0,
  470.0,
  529.0,
  530.0,
  640.0,
  641.0,
  698.0,
  699.0,
  753.0,
  754.0,
  867.0,
  868.0,
  923.0,
  924.0,
  1037.0,
  1038.0,
  1103.0,
  104.0,
  245.0,
  246.0,
  358.0,
  359.0,
  480.0,
  524.0,
  592.0,
  622.0,
  687.0,
  722.0,
  773.0,
  774.0,
  885.0,
  886.0,
  1063.0,
  557.0,
  629.0,
  630.0,
  688.0,
  689.0,
  800.0,
  801.0,
  844.0,
  845.0,
  956.0,
  957.0,
  1037.0,
  557.0,
  688.0,
  689.0,
  748.0,
  749.0,
  858.0,
  859.0,
  898.0,
  899.0,
  956.0,
  957.0,
  1000.0,
  1001.0,
  1110.0,
  1111.0,
  1183.0,
  557.0,
  609.0,
  610.0,
  645.0,
  646.0,
  680.0,
  681.0,
  715.0,
  716.0,
  780.0],
 [120.0,
  201.0,
  202.0,
  312.0,
  313.0,
  374.0,
  375.0,
  429.0,
  430.0,
  492.0,
  536.0,
  655.0,
  656.0,
  714.0,
  715.0,
  835.0,
  874.0,
  940.0,
  941.0,
  997.0,
  998.0,
  1054.0,
  1055.0,
  1130.0,
  120.0,
  201.0,
  202.0,
  312.0,
  313.0,
  374.0,
  375.0,
  429.0,
  430.0,
  487.0,
  488.0,
  600.0,
  601.0,
  657.0,
  658.0,
  777.0,
  775.0,
  917.0,
  775.0,
  917.0,
  775.0,
  917.0],
 [110.0,
  193.0,
  194.0,
  364.0,
  365.0,
  475.0,
  4786.0,
  588.0,
  589.0,
  647.0,
  648.0,
  710.0,
  750.0,
  874.0,
  875.0,
  998.0,
  1035.0,
  1122.0,
  110.0,
  193.0,
  194.0,
  249.0,
  250.0,
  309.0,
  310.0,
  360.0,
  361.0,
  486.0,
  525.0,
  648.0,
  649.0,
  761.0,
  762.0,
  819.0,
  820.0,
  875.0,
  876.0,
  930.0,
  931.0,
  991.0,
  992.0,
  1111.0,
  648.0,
  727.0,
  728.0,
  840.0,
  841.0,
  973.0,
  648.0,
  727.0,
  728.0,
  783.0,
  784.0,
  923.0,
  648.0,
  727.0,
  728.0,
  840.0,
  841.0,
  954.0,
  955.0,
  1012.0,
  1013.0,
  1138.0],
 [143.0,
  222.0,
  223.0,
  332.0,
  333.0,
  393.0,
  394.0,
  451.0,
  452.0,
  506.0,
  507.0,
  676.0,
  677.0,
  794.0,
  795.0,
  857.0,
  895.0,
  960.0,
  961.0,
  1094.0,
  143.0,
  279.0,
  280.0,
  397.0,
  740.0,
  858.0,
  859.0,
  999.0,
  740.0,
  803.0,
  804.0,
  918.0,
  919.0,
  1050.0,
  740.0,
  858.0,
  859.0,
  918.0,
  919.0,
  1050.0],
 [125.0,
  266.0,
  267.0,
  323.0,
  324.0,
  378.0,
  379.0,
  436.0,
  437.0,
  490.0,
  491.0,
  607.0,
  608.0,
  664.0,
  665.0,
  787.0,
  820.0,
  946.0,
  947.0,
  1062.0,
  1063.0,
  1134.0,
  125.0,
  275.0,
  311.0,
  438.0,
  439.0,
  490.0,
  491.0,
  602.0,
  603.0,
  722.0,
  723.0,
  776.0,
  777.0,
  898.0,
  667.0,
  732.0,
  733.0,
  788.0,
  789.0,
  849.0,
  850.0,
  962.0,
  963.0,
  1098.0,
  667.0,
  732.0,
  733.0,
  788.0,
  789.0,
  908.0,
  909.0,
  962.0,
  963.0,
  1098.0,
  667.0,
  732.0,
  733.0,
  788.0,
  789.0,
  908.0,
  909.0,
  962.0,
  963.0,
  1098.0],
 [135.0,
  222.0,
  223.0,
  349.0,
  350.0,
  412.0,
  413.0,
  479.0,
  480.0,
  541.0,
  542.0,
  681.0,
  720.0,
  858.0,
  859.0,
  987.0,
  988.0,
  1056.0,
  135.0,
  228.0,
  272.0,
  352.0,
  353.0,
  409.0,
  410.0,
  477.0,
  478.0,
  540.0,
  541.0,
  668.0,
  799.0,
  942.0,
  799.0,
  942.0,
  799.0,
  915.0,
  916.0,
  1046.0],
 [111.0,
  250.0,
  251.0,
  304.0,
  305.0,
  420.0,
  421.0,
  600.0,
  638.0,
  760.0,
  761.0,
  875.0,
  876.0,
  990.0,
  991.0,
  1044.0,
  1045.0,
  1122.0,
  111.0,
  193.0,
  194.0,
  248.0,
  249.0,
  424.0,
  425.0,
  480.0,
  481.0,
  536.0,
  537.0,
  588.0,
  589.0,
  647.0,
  648.0,
  714.0,
  752.0,
  828.0,
  829.0,
  884.0,
  885.0,
  968.0,
  752.0,
  828.0,
  829.0,
  884.0,
  885.0,
  968.0,
  752.0,
  828.0,
  829.0,
  884.0,
  885.0,
  999.0,
  1000.0,
  1053.0,
  1054.0,
  1130.0],
 [111.0,
  187.0,
  188.0,
  309.0,
  310.0,
  366.0,
  367.0,
  423.0,
  424.0,
  590.0,
  591.0,
  704.0,
  705.0,
  818.0,
  819.0,
  874.0,
  875.0,
  1002.0,
  111.0,
  192.0,
  193.0,
  249.0,
  250.0,
  364.0,
  365.0,
  478.0,
  479.0,
  598.0,
  755.0,
  885.0,
  886.0,
  944.0,
  945.0,
  998.0,
  999.0,
  1133.0,
  755.0,
  885.0,
  886.0,
  1003.0,
  1004.0,
  1054.0,
  1055.0,
  1133.0,
  755.0,
  831.0,
  832.0,
  886.0,
  887.0,
  943.0,
  944.0,
  1015.0],
 [133.0,
  387.0,
  388.0,
  500.0,
  501.0,
  670.0,
  671.0,
  740.0,
  777.0,
  842.0,
  843.0,
  956.0,
  957.0,
  1075.0,
  665.0,
  735.0,
  736.0,
  793.0,
  794.0,
  852.0,
  853.0,
  1023.0,
  1024.0,
  1095.0,
  665.0,
  735.0,
  736.0,
  850.0,
  851.0,
  906.0,
  907.0,
  966.0,
  967.0,
  1045.0,
  665.0,
  735.0,
  736.0,
  850.0,
  851.0,
  906.0,
  907.0,
  966.0,
  967.0,
  1045.0],
 [180.0,
  249.0,
  250.0,
  304.0,
  305.0,
  344.0,
  345.0,
  459.0,
  460.0,
  587.0,
  615.0,
  668.0,
  669.0,
  725.0,
  726.0,
  768.0,
  769.0,
  886.0,
  887.0,
  1009.0,
  180.0,
  266.0,
  267.0,
  381.0,
  382.0,
  443.0,
  790.0,
  836.0,
  837.0,
  870.0,
  871.0,
  910.0,
  911.0,
  944.0,
  945.0,
  982.0,
  983.0,
  1014.0,
  1015.0,
  1074.0,
  790.0,
  836.0,
  837.0,
  870.0,
  871.0,
  910.0,
  911.0,
  944.0,
  945.0,
  982.0,
  983.0,
  1014.0,
  1015.0,
  1074.0,
  790.0,
  915.0,
  916.0,
  995.0],
 [112.0,
  192.0,
  193.0,
  251.0,
  252.0,
  308.0,
  309.0,
  366.0,
  367.0,
  422.0,
  423.0,
  480.0,
  481.0,
  592.0,
  593.0,
  835.0,
  836.0,
  899.0,
  935.0,
  1000.0,
  1001.0,
  1134.0,
  112.0,
  247.0,
  248.0,
  370.0,
  740.0,
  862.0,
  863.0,
  991.0,
  740.0,
  801.0,
  802.0,
  918.0,
  919.0,
  1045.0,
  740.0,
  862.0,
  863.0,
  915.0,
  916.0,
  1045.0],
 [113.0,
  306.0,
  307.0,
  363.0,
  364.0,
  533.0,
  534.0,
  648.0,
  649.0,
  770.0,
  805.0,
  875.0,
  876.0,
  986.0,
  987.0,
  1121.0,
  113.0,
  193.0,
  194.0,
  248.0,
  249.0,
  368.0,
  739.0,
  859.0,
  860.0,
  993.0,
  739.0,
  859.0,
  860.0,
  993.0,
  739.0,
  859.0,
  860.0,
  993.0],
 [113.0,
  250.0,
  251.0,
  308.0,
  309.0,
  480.0,
  481.0,
  535.0,
  536.0,
  595.0,
  596.0,
  750.0,
  751.0,
  830.0,
  866.0,
  991.0,
  992.0,
  1121.0,
  113.0,
  306.0,
  307.0,
  362.0,
  363.0,
  419.0,
  420.0,
  476.0,
  477.0,
  535.0,
  536.0,
  600.0,
  638.0,
  705.0,
  706.0,
  760.0,
  761.0,
  930.0,
  931.0,
  997.0,
  674.0,
  777.0,
  674.0,
  821.0,
  674.0,
  745.0,
  746.0,
  803.0,
  804.0,
  917.0,
  918.0,
  1105.0],
 [219.0,
  358.0,
  359.0,
  414.0,
  415.0,
  470.0,
  471.0,
  583.0,
  584.0,
  644.0,
  645.0,
  704.0,
  744.0,
  869.0,
  870.0,
  988.0,
  758.0,
  829.0,
  830.0,
  903.0,
  758.0,
  829.0,
  830.0,
  903.0,
  758.0,
  903.0],
 [113.0,
  306.0,
  307.0,
  365.0,
  366.0,
  476.0,
  477.0,
  533.0,
  534.0,
  650.0,
  651.0,
  770.0,
  813.0,
  875.0,
  876.0,
  990.0,
  991.0,
  1056.0,
  113.0,
  191.0,
  192.0,
  250.0,
  251.0,
  307.0,
  308.0,
  420.0,
  421.0,
  476.0,
  477.0,
  541.0,
  737.0,
  930.0,
  737.0,
  930.0,
  737.0,
  855.0,
  856.0,
  930.0],
 [111.0,
  191.0,
  192.0,
  249.0,
  250.0,
  307.0,
  308.0,
  421.0,
  422.0,
  535.0,
  536.0,
  658.0,
  697.0,
  762.0,
  763.0,
  820.0,
  821.0,
  937.0,
  938.0,
  1046.0,
  111.0,
  200.0,
  240.0,
  307.0,
  308.0,
  362.0,
  363.0,
  532.0,
  533.0,
  650.0,
  651.0,
  715.0,
  750.0,
  878.0,
  879.0,
  931.0,
  932.0,
  1043.0,
  111.0,
  191.0,
  192.0,
  315.0,
  740.0,
  826.0,
  827.0,
  918.0,
  919.0,
  972.0,
  973.0,
  1057.0,
  740.0,
  826.0,
  827.0,
  918.0,
  919.0,
  972.0,
  973.0,
  1057.0,
  740.0,
  804.0,
  805.0,
  861.0,
  862.0,
  918.0,
  919.0,
  1032.0,
  1033.0,
  1165.0],
 [113.0,
  247.0,
  248.0,
  365.0,
  366.0,
  419.0,
  420.0,
  485.0,
  524.0,
  645.0,
  646.0,
  763.0,
  764.0,
  875.0,
  876.0,
  933.0,
  934.0,
  989.0,
  990.0,
  1121.0,
  113.0,
  190.0,
  191.0,
  433.0,
  469.0,
  590.0,
  591.0,
  704.0,
  705.0,
  763.0,
  764.0,
  820.0,
  821.0,
  873.0,
  874.0,
  932.0,
  933.0,
  1056.0,
  690.0,
  764.0,
  765.0,
  822.0,
  823.0,
  877.0,
  878.0,
  959.0,
  690.0,
  764.0,
  765.0,
  822.0,
  823.0,
  877.0,
  878.0,
  959.0,
  690.0,
  764.0,
  765.0,
  822.0,
  823.0,
  877.0,
  878.0,
  995.0,
  996.0,
  1061.0],
 [108,
  186,
  218,
  283,
  316,
  382,
  412,
  481,
  513,
  560,
  561,
  616,
  617,
  671,
  672,
  791,
  792,
  914,
  950,
  1016,
  1017,
  1072,
  1073,
  1144,
  108,
  251,
  252,
  363,
  364,
  477,
  478,
  590,
  591,
  711,
  739,
  783,
  784,
  815,
  816,
  856,
  857,
  887,
  888,
  923,
  924,
  958,
  959,
  999,
  1000,
  1034,
  1035,
  1091,
  739,
  783,
  784,
  815,
  816,
  856,
  857,
  887,
  888,
  923,
  924,
  958,
  959,
  999,
  1000,
  1034,
  1035,
  1091,
  739,
  783,
  784,
  815,
  816,
  856,
  857,
  887,
  888,
  923,
  924,
  958,
  959,
  999,
  1000,
  1034,
  1035,
  1091],
 [111.0,
  190.0,
  191.0,
  310.0,
  311.0,
  479.0,
  480.0,
  533.0,
  534.0,
  646.0,
  647.0,
  706.0,
  707.0,
  830.0,
  865.0,
  931.0,
  932.0,
  991.0,
  992.0,
  1045.0,
  111.0,
  192.0,
  193.0,
  305.0,
  306.0,
  373.0,
  412.0,
  536.0,
  537.0,
  592.0,
  593.0,
  646.0,
  647.0,
  705.0,
  706.0,
  826.0,
  755.0,
  833.0,
  834.0,
  1020.0,
  755.0,
  833.0,
  834.0,
  1020.0,
  755.0,
  833.0,
  834.0,
  1020.0],
 [175.0,
  370.0,
  371.0,
  482.0,
  483.0,
  540.0,
  541.0,
  655.0,
  656.0,
  767.0,
  768.0,
  878.0,
  879.0,
  939.0,
  940.0,
  1002.0,
  175.0,
  251.0,
  252.0,
  313.0,
  314.0,
  367.0,
  368.0,
  489.0,
  755.0,
  828.0,
  829.0,
  911.0,
  755.0,
  828.0,
  829.0,
  911.0,
  755.0,
  890.0,
  891.0,
  963.0],
 [51,
  195,
  196,
  310,
  311,
  420,
  421,
  477,
  478,
  590,
  591,

In [184]:
# # special Q XXXXXXXXXXXXX
# special_Q = [5,6,18,29,31,39,42,44,46]
# special_Q_forloop = list(np.subtract(np.array(special_Q), np.array([1]*len(special_Q)))) #[4, 5, 17, 28, 30, 38, 41, 43, 45]

# fixation_total = []
# for k in range(len(x_AOI_range)):
#     if k in special_Q_forloop:
#         continue
#     fixation_list = []
#     for i in range(len(x_AOI_range[k])//2):
#         inrange_df = df_time[(df_time['x'] >= int(x_AOI_range[k][2*i])) & (df_time['x'] <= int(x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(y_AOI_range[k][2*i])) & (df_time['y'] <= int(y_AOI_range[k][2*i+1]))]
#         if inrange_df.empty:
#             fixation_list.append(0)
#         else:
#             fixation_list.append(1)
#     fixation_total.append(fixation_list)
# len(fixation_total)

# ############################
# normal_Q_index = [item for item in list(range(1,48)) if item not in set(special_Q)]
# normal_Q_index_df = pd.DataFrame(normal_Q_index)
# normal_Q_index_df.columns = ["Q_index"]

# ###########################
# word_Q_count = []
# for i in range(len(fixation_total)):
#     word_Q_count.append(len(fixation_total[i]))
# word_Q_count_df = pd.DataFrame(word_Q_count)
# word_Q_count_df.columns = ["word_count"]

# ###########################
# # combine "normal_Q_index", "word_Q_count", "fixation_total"
# normalQ_wordcount_df = pd.concat([normal_Q_index_df, word_Q_count_df, pd.DataFrame(fixation_total)], axis = 1)  # .reset_index(drop=True)
# normalQ_wordcount_df.to_csv ("/Users/apple/Desktop/deep_eye/dataset/word_fixation/normalQ_wordcount.csv", index = None, header=True) 
# normalQ_wordcount_df

,Q_index,word_count,0,1,2,3,4,5,6,7,...,34,35,36,37,38,39,40,41,42,43
0,1,26,0,0,1,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,28,0,1,1,0,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,20,0,1,1,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,19,0,1,0,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,14,1,1,1,0,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,8,37,0,0,0,1,1,0,0,0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,9,16,0,1,1,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10,34,0,1,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,11,27,0,1,1,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,12,26,0,0,1,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,13,27,0,1,1,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,14,20,0,1,0,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15,38,0,1,1,1,1,0,0,1,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,16,16,0,1,1,0,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,17,26,0,1,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,19,20,0,0,1,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,20,22,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,21,19,0,1,1,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,22,29,1,0,1,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,23,20,0,1,1,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,24,39,0,1,1,0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
21,25,23,0,1,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,26,32,0,1,1,0,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,27,20,0,1,1,0,1,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,28,33,0,1,0,1,1,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,30,28,0,1,1,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,32,22,1,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,33,29,0,1,1,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,34,21,0,0,1,0,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,35,17,1,0,1,0,1,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,36,25,0,1,1,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,37,13,1,1,0,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,38,19,1,0,1,1,0,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,40,32,0,1,1,1,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,41,44,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,43,18,1,1,1,0,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,45,27,1,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,47,18,0,1,1,0,0,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---
## ignore special Q
手動刪除special Q 的跨行座標，將跨行先視為第一行的座標，手動檢查下面行
>第一行的fixation皆為0，可以以第二行的座標為主

In [50]:
df_time

      start_time       x      y  duration
9943     2790252  1080.8  288.1       190
9946     2790911   593.2  426.1       170
9947     2791126   439.5  721.8       138
9950     2791490   908.4  592.1       110
9951     2791688   322.9  763.2       199
9954     2792329   547.7  308.8       253
9955     2792627   381.8  327.6       201
9958     2793083   342.2  435.2       359
9959     2793465   245.5  435.5       131
9961     2793928   887.9  537.7       216
9964     2794483   801.5  600.8       148
9966     2794851   960.7  294.2       109
9968     2795172  1096.3  291.9       208
9970     2795582   340.2  328.2       140
9971     2795923   576.3  300.6       198
9973     2796195   479.3  333.0       150
9974     2796408   828.8  748.3       171
9976     2797095   464.5  702.5       188
9977     2797314   395.9  742.9       141
9979     2797740   433.7  711.8       199
9984     2798580   367.7  755.7       194

In [49]:
k=0
All_fixation_list = []
for i in range(len(All_x_AOI_range[k])//2):
    inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
    print("x1:",int(All_x_AOI_range[k][2*i]))
    print("x2:",int(All_x_AOI_range[k][2*i+1]))
    print("y1:",int(All_y_AOI_range[k][2*i]))
    print("y2:",int(All_y_AOI_range[k][2*i+1]))
    print(i,"!!!!!!",inrange_df)
    if inrange_df.empty:
        print(0)
        # All_fixation_list.append(0)
    else:
        print(1)
        # All_fixation_list.append(1)
#print(All_fixation_list)

x1: 117
x2: 190
y1: 192
y2: 291
0 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 191
x2: 250
y1: 192
y2: 291
1 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 251
x2: 365
y1: 192
y2: 291
2 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 366
x2: 425
y1: 192
y2: 291
3 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 426
x2: 475
y1: 192
y2: 291
4 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 476
x2: 540
y1: 192
y2: 291
5 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 541
x2: 595
y1: 192
y2: 291
6 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 596
x2: 652
y1: 192
y2: 291
7 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 653
x2: 710
y1: 192
y2: 291
8 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 711
x2: 775
y1: 192
y2: 291
9 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 776
x2: 833
y1: 192
y2: 291
10 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 834
x2: 950
y1: 192
y2: 291
11 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 1000
x2: 1141
y1: 192
y2: 291
12 !!!!!!       start_time       x      y  duration
9943     2790252  1080.8  288.1       190
1
x1: 117
x2: 190
y1: 193
y2: 390
13 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 191
x2: 250
y1: 193
y2: 390
14 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 251
x2: 365
y1: 193
y2: 390
15 !!!!!!       start_time      x      y  duration
9970     2795582  340.2  328.2       140
1
x1: 366
x2: 435
y1: 193
y2: 390
16 !!!!!!       start_time      x      y  duration
9955     2792627  381.8  327.6       201
1
x1: 755
x2: 888
y1: 470
y2: 577
17 !!!!!!       start_time      x      y  duration
9961     2793928  887.9  537.7       216
1
x1: 889
x2: 978
y1: 470
y2: 577
18 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 979
x2: 1053
y1: 470
y2: 577
19 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 755
x2: 888
y1: 578
y2: 691
20 !!!!!!       start_time      x      y  duration
9964     2794483  801.5  600.8       148
1
x1: 889
x2: 978
y1: 578
y2: 691
21 !!!!!!       start_time      x      y  duration
9950     2791490  908.4  592.1       110
1
x1: 979
x2: 1053
y1: 578
y2: 691
22 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 755
x2: 888
y1: 692
y2: 795
23 !!!!!!       start_time      x      y  duration
9974     2796408  828.8  748.3       171
1
x1: 889
x2: 978
y1: 685
y2: 795
24 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0
x1: 979
x2: 1053
y1: 685
y2: 795
25 !!!!!! Empty DataFrame
Columns: [start_time, x, y, duration]
Index: []
0

In [54]:
# 一個人
x_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_x_2ndline.csv")
y_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_y_2ndline.csv")

word_per_page_count = x_raw.iloc[-1, 1:]

x_AOI = x_raw.iloc[:-1, 1:]
y_AOI = y_raw.iloc[:-1, 1:]

All_x_AOI_range = []
for i in range(x_AOI.shape[1]):
    xpage = x_AOI.iloc[:,i]
    All_x_AOI_range.append(list(xpage[xpage.notna()]))

All_y_AOI_range = []
for i in range(y_AOI.shape[1]):
    ypage = y_AOI.iloc[:,i]
    All_y_AOI_range.append(list(ypage[ypage.notna()]))

    

All_fixation_total = []
for k in range(len(All_x_AOI_range)):
    All_fixation_list = []
    for i in range(len(All_x_AOI_range[k])//2):
        inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
        if inrange_df.empty:
            All_fixation_list.append(0)
        else:
            All_fixation_list.append(1)
    print(All_fixation_list)
    All_fixation_total.append(All_fixation_list)
#len(All_fixation_total) #47


# ######################################################
# All_word_Q_count = []
# for i in range(len(All_fixation_total)):
#     All_word_Q_count.append(len(All_fixation_total[i]))
# All_word_Q_count_df = pd.DataFrame(All_word_Q_count)
# All_word_Q_count_df.columns = ["word_count"]

# ######################################################
# # combine "All_word_Q_count" & "All_fixation_total"
# All_normalQ_wordcount_df = pd.concat([All_word_Q_count_df, pd.DataFrame(All_fixation_total)], axis = 1)  # .reset_index(drop=True)
# All_normalQ_wordcount_df.to_csv ("/Users/apple/Desktop/deep_eye/dataset/word_fixation/All_normalQ_wordcount.csv", index = None, header=True) 
# All_normalQ_wordcount_df

[0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0]
[0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0]
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0]
[0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
[0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0]
[0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1]
[0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0]
[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0]
[1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
[1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0]
[1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0]
[0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1]
[1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0]
[0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0]
[0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0]

In [59]:
pd.DataFrame(All_fixation_total[0]).T

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0,0,1,1,0,1,0,0,0,1,...,1,1,1,1,1,1,0,0,1,0

# 文字處理

In [103]:
word_df_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_text.csv").iloc[:-2,2:]
word_nona_list = []
for i in range(len(word_df_raw.values)):
    word_nona_list.append([x for x in word_df_raw.values[i] if pd.isna(x) == False])

word_df = pd.DataFrame(sum(word_nona_list, []))
word_df.columns = ["text"]
word_df

     text
0       兩
1       個
2      量筒
3       各
4       裝
...   ...
1216   變化
1217   變大
1218   變小
1219   不會
1220   改變

[1221 rows x 1 columns]

In [296]:
All_fixation_QID_df = pd.DataFrame()
for i in range(len(All_fixation_total)):
    df = pd.DataFrame(All_fixation_total[i])
    df['Q_ID'] = str(i+1)
    All_fixation_QID_df = pd.concat([All_fixation_QID_df, df], axis = 0).reset_index(drop=True)
All_fixation_QID_df.columns = ["fixation1", "Q_ID"]
All_fixation_QID_df

      fixation1 Q_ID
0             0    1
1             0    1
2             1    1
3             1    1
4             0    1
...         ...  ...
1216          0   47
1217          1   47
1218          0   47
1219          0   47
1220          0   47

[1221 rows x 2 columns]

In [298]:
input_data = pd.concat([All_fixation_QID_df, word_df], axis = 1)
input_data = input_data[['Q_ID', 'text', 'fixation1']]
input_data.to_csv ("/Users/apple/Desktop/deep_eye/dataset/input_data.csv", index = None, header=True) 
input_data

     Q_ID text  fixation1
0       1    兩          0
1       1    個          0
2       1   量筒          1
3       1    各          1
4       1    裝          0
...   ...  ...        ...
1216   47   變化          0
1217   47   變大          1
1218   47   變小          0
1219   47   不會          0
1220   47   改變          0

[1221 rows x 3 columns]

# 正式全部人

In [84]:
x_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_x_2ndline.csv")
y_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_y_2ndline.csv")

word_per_page_count = x_raw.iloc[-1, 1:]

x_AOI = x_raw.iloc[:-1, 1:]
y_AOI = y_raw.iloc[:-1, 1:]

All_x_AOI_range = []
for i in range(x_AOI.shape[1]):
    xpage = x_AOI.iloc[:,i]
    All_x_AOI_range.append(list(xpage[xpage.notna()]))

All_y_AOI_range = []
for i in range(y_AOI.shape[1]):
    ypage = y_AOI.iloc[:,i]
    All_y_AOI_range.append(list(ypage[ypage.notna()]))


# 文字
word_df_raw = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/AOI/AOI_text.csv").iloc[:-2,2:]
word_nona_list = []
for i in range(len(word_df_raw.values)):
    word_nona_list.append([x for x in word_df_raw.values[i] if pd.isna(x) == False])

word_df = pd.DataFrame(sum(word_nona_list, []))
word_df.columns = ["text"]
# word_df

In [98]:
word_df

     text
0       兩
1       個
2      量筒
3       各
4       裝
...   ...
1216   變化
1217   變大
1218   變小
1219   不會
1220   改變

[1221 rows x 1 columns]

In [97]:
All_fixation_QID_df

    fixation1 Q_ID
0           0    1
1           0    1
2           1    1
3           1    1
4           0    1
5           1    1
6           0    1
7           0    1
8           0    1
9           1    1
10          1    1
11          1    1
12          1    1
13          0    1
14          0    1
15          1    1
16          1    1
17          1    1
18          1    1
19          1    1
20          1    1
21          1    1
22          0    1
23          0    1
24          1    1
25          0    1

In [100]:

#第一個人
origin_path = "/Users/apple/Desktop/deep_eye/dataset/raw_A/"

total_input_data = pd.DataFrame()

path_csv = origin_path + "A0" + str(1) + ".csv"
df = pd.read_csv(path_csv)
df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
df_col.columns = ['start_time', 'x', 'y', 'duration']

# form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
perQ_fixation_QID_df = pd.DataFrame()
for q in range(1,3): #range(1,48)
    if int(resp_array[p-1][q-1]) == 0:
        df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
    else:
        df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
    df_time = df_time[(df_time['duration']>= 100)] # duration >= 100

    #All_fixation_total = []
    k=q-1
    All_fixation_list = []
    for i in range(len(All_x_AOI_range[k])//2):
        inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
        if inrange_df.empty:
            All_fixation_list.append(0)
        else:
            All_fixation_list.append(1)
    All_fixation_total = All_fixation_list#All_fixation_total.append(All_fixation_list)
    # len(All_fixation_total) #47
    

    All_fixation_QID_df = pd.DataFrame(All_fixation_total)# df = pd.DataFrame(All_fixation_total[i])
    All_fixation_QID_df['Q_ID'] = str(q)
    All_fixation_QID_df.columns = ["fixation1", "Q_ID"]

    perQ_fixation_QID_df = pd.concat([perQ_fixation_QID_df,All_fixation_QID_df], axis = 0)
    #input_data = input_data[['Q_ID', 'text', 'fixation1']]
perQ_fixation_QID_df

    fixation1 Q_ID
0           0    1
1           0    1
2           1    1
3           1    1
4           0    1
5           1    1
6           0    1
7           0    1
8           0    1
9           1    1
10          1    1
11          1    1
12          1    1
13          0    1
14          0    1
15          1    1
16          1    1
17          1    1
18          1    1
19          1    1
20          1    1
21          1    1
22          0    1
23          0    1
24          1    1
25          0    1
0           0    2
1           0    2
2           1    2
3           1    2
4           1    2
5           0    2
6           0    2
7           0    2
8           1    2
9           0    2
10          1    2
11          0    2
12          1    2
13          1    2
14          1    2
15          0    2
16          1    2
17          1    2
18          1    2
19          1    2
20          1    2
21          1    2
22          0    2
23          0    2
24          0    2
25          1    2
26          1    2
27          1    2

In [17]:

# #第一個人
# origin_path = "/Users/apple/Desktop/deep_eye/dataset/raw_A/"

# total_input_data = pd.DataFrame()

# path_csv = origin_path + "A0" + str(1) + ".csv"
# df = pd.read_csv(path_csv)
# df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
# df_col.columns = ['start_time', 'x', 'y', 'duration']

# # form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
# for q in range(1,48):
#     if int(resp_array[p-1][q-1]) == 0:
#         df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
#     else:
#         df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
#     df_time = df_time[(df_time['duration']>= 100)] # duration >= 100


#     All_fixation_total = []
#     for k in range(len(All_x_AOI_range)):
#         All_fixation_list = []
#         for i in range(len(All_x_AOI_range[k])//2):
#             inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
#             if inrange_df.empty:
#                 All_fixation_list.append(0)
#             else:
#                 All_fixation_list.append(1)
#         All_fixation_total.append(All_fixation_list)
#     # len(All_fixation_total) #47
    
#     All_fixation_QID_df = pd.DataFrame()
#     for i in range(len(All_fixation_total)):
#         df = pd.DataFrame(All_fixation_total[i])
#         df['Q_ID'] = str(i+1)
#         All_fixation_QID_df = pd.concat([All_fixation_QID_df, df], axis = 0).reset_index(drop=True)
#     All_fixation_QID_df.columns = ["fixation1", "Q_ID"]

#     input_data = pd.concat([All_fixation_QID_df, word_df], axis = 1)
#     input_data = input_data[['Q_ID', 'text', 'fixation1']]
# input_data

     Q_ID text  fixation1
0       1    兩          0
1       1    個          0
2       1   量筒          0
3       1    各          0
4       1    裝          0
...   ...  ...        ...
1216   47   變化          0
1217   47   變大          1
1218   47   變小          1
1219   47   不會          0
1220   47   改變          0

[1221 rows x 3 columns]

In [111]:
####!!!!!!!! done######

origin_path = "/Users/apple/Desktop/deep_eye/dataset/raw_C/"

total_perQ_fixation_QID_df = pd.DataFrame()
for p in range(1,31):
    if p <= 9:
        path_csv = origin_path + "C0" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
        df_col.columns = ['start_time', 'x', 'y', 'duration']
        
        # form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
        perQ_fixation_QID_df = pd.DataFrame()
        for q in range(1,48): 
            if int(resp_array[p-1][q-1]) == 0:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
            else:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
            df_time = df_time[(df_time['duration']>= 100)] # duration >= 100

            #All_fixation_total = []
            k=q-1
            All_fixation_list = []
            for i in range(len(All_x_AOI_range[k])//2):
                inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
                if inrange_df.empty:
                    All_fixation_list.append(0)
                else:
                    All_fixation_list.append(1)
            All_fixation_total = All_fixation_list#All_fixation_total.append(All_fixation_list)
            # len(All_fixation_total) #47
            

            All_fixation_QID_df = pd.DataFrame(All_fixation_total)# df = pd.DataFrame(All_fixation_total[i])
            All_fixation_QID_df['Q_ID'] = str(q)
            All_fixation_QID_df.columns = ["fixation1", "Q_ID"]

            perQ_fixation_QID_df = pd.concat([perQ_fixation_QID_df,All_fixation_QID_df], axis = 0)
            #input_data = input_data[['Q_ID', 'text', 'fixation1']]
        #perQ_fixation_QID_df #1~47 fixation and Q_ID
        perQ_fixation_QID_df = pd.concat([perQ_fixation_QID_df.reset_index(drop=True), word_df], axis = 1)
        perQ_fixation_QID_df = perQ_fixation_QID_df[['Q_ID', 'text', 'fixation1']]
        # input_data.to_csv ("/Users/apple/Desktop/deep_eye/dataset/input_data.csv", index = None, header=True) 
      
    else:
        path_csv = origin_path + "C" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
        df_col.columns = ['start_time', 'x', 'y', 'duration']
        
        # form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
        perQ_fixation_QID_df = pd.DataFrame()
        for q in range(1,48): 
            if int(resp_array[p-1][q-1]) == 0:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
            else:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
            df_time = df_time[(df_time['duration']>= 100)] # duration >= 100

            #All_fixation_total = []
            k=q-1
            All_fixation_list = []
            for i in range(len(All_x_AOI_range[k])//2):
                inrange_df = df_time[(df_time['x'] >= int(All_x_AOI_range[k][2*i])) & (df_time['x'] <= int(All_x_AOI_range[k][2*i+1])) & (df_time['y'] >= int(All_y_AOI_range[k][2*i])) & (df_time['y'] <= int(All_y_AOI_range[k][2*i+1]))]
                if inrange_df.empty:
                    All_fixation_list.append(0)
                else:
                    All_fixation_list.append(1)
            All_fixation_total = All_fixation_list#All_fixation_total.append(All_fixation_list)
            # len(All_fixation_total) #47
            

            All_fixation_QID_df = pd.DataFrame(All_fixation_total)# df = pd.DataFrame(All_fixation_total[i])
            All_fixation_QID_df['Q_ID'] = str(q)
            All_fixation_QID_df.columns = ["fixation1", "Q_ID"]

            perQ_fixation_QID_df = pd.concat([perQ_fixation_QID_df,All_fixation_QID_df], axis = 0)
            #input_data = input_data[['Q_ID', 'text', 'fixation1']]
        #perQ_fixation_QID_df #1~47 fixation and Q_ID
        perQ_fixation_QID_df = pd.concat([perQ_fixation_QID_df.reset_index(drop=True), word_df], axis = 1)
        perQ_fixation_QID_df = perQ_fixation_QID_df[['Q_ID', 'text', 'fixation1']]
        # input_data.to_csv ("/Users/apple/Desktop/deep_eye/dataset/input_data.csv", index = None, header=True) 
    
    perQ_fixation_QID_df["participant_ID"] = str(p+30)
    total_perQ_fixation_QID_df = pd.concat([total_perQ_fixation_QID_df, perQ_fixation_QID_df],axis=0)
    print(p)
total_perQ_fixation_QID_df
total_perQ_fixation_QID_df.to_csv("/Users/apple/Desktop/deep_eye/dataset/input_dataC.csv")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

In [112]:
total_perQ_fixation_QID_df

     Q_ID text  fixation1 participant_ID
0       1    兩          0             31
1       1    個          0             31
2       1   量筒          1             31
3       1    各          0             31
4       1    裝          1             31
...   ...  ...        ...            ...
1216   47   變化          0             60
1217   47   變大          0             60
1218   47   變小          0             60
1219   47   不會          0             60
1220   47   改變          0             60

[36630 rows x 4 columns]

In [113]:
A_df = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/input_dataA.csv").iloc[:,1:]
C_df = pd.read_csv("/Users/apple/Desktop/deep_eye/dataset/input_dataC.csv").iloc[:,1:]
inputdata_AC = pd.concat([A_df, C_df],axis=0)
inputdata_AC = inputdata_AC[['participant_ID', 'Q_ID', 'text', 'fixation1']]
inputdata_AC.to_csv("/Users/apple/Desktop/deep_eye/dataset/input_data.csv")
inputdata_AC

       participant_ID  Q_ID text  fixation1
0                   1     1    兩          0
1                   1     1    個          0
2                   1     1   量筒          1
3                   1     1    各          1
4                   1     1    裝          0
...               ...   ...  ...        ...
36625              60    47   變化          0
36626              60    47   變大          0
36627              60    47   變小          0
36628              60    47   不會          0
36629              60    47   改變          0

[73260 rows x 4 columns]

In [114]:
(inputdata_AC['fixation1'] == 1).sum()

23995

---

In [ ]:
## AOI corrdinate OK ## 

AOI_cor = pd.read_csv("/Users/apple/Desktop/202108eyeml/P1_AOI_corrdinate.csv",index_col=0)
# separate x and y
x_cor = AOI_cor.iloc[:, [0,2,4,6,8,10]]
y_cor = AOI_cor.iloc[:, [1,3,5,7,9,11]]
print(x_cor.head())
print(y_cor.head())

   QULX  QLRX  CULX  CLRX  PULX  PLRX
1   117  1141   642  1053   145   597
2   155  1097   433  1184   166   432
3   109  1120   657   936   127   655
4   114  1121   663  1104   122   662
5   112  1122   591  1138   175   590
   QULY  QLRY  CULY  CLRY  PULY  PLRY
1   192   390   470   792   413   818
2   184   382   486   815   401   860
3   240   438   493   819   456   881
4   230   430   509   839   522   829
5   202   400   477   805   438   822

In [28]:
# keep column : "start time", "x", "y", "duration"
# cut time according to onset data
# delete all points outside AOI QCP

origin_path = "/Users/apple/Desktop/202108eyeml/A/AP1_check/origin/"

for p in range(1,31):
    if p <= 9:
        path_csv = origin_path + "A0" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
        df_col.columns = ['start_time', 'x', 'y', 'duration']
        
        # form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
        QCP_combine = pd.DataFrame(columns=['start_time', 'x', 'y', 'duration']) # empty df
        QCP = []
        QCP_duration = []
        for q in range(1,48):
            if int(resp_array[p-1][q-1]) == 0:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
            else:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
            ## df_cor = df_time[(df_time['x'] >= x_cor.iloc[q-1].min()) & (df_time['x'] <= x_cor.iloc[q-1].max()) & (df_time['y'] >= y_cor.iloc[q-1].min()) & (df_time['y'] <= y_cor.iloc[q-1].max())] # xy in AOI
            df_time = df_time[(df_time['duration']>= 100)] # duration >= 100

            Q = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][0])) & (df_time['x'] <= int(x_cor.iloc[q-1][1])) & (df_time['y'] >= int(y_cor.iloc[q-1][0])) & (df_time['y'] <= int(y_cor.iloc[q-1][1]))]
            C = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][2])) & (df_time['x'] <= int(x_cor.iloc[q-1][3])) & (df_time['y'] >= int(y_cor.iloc[q-1][2])) & (df_time['y'] <= int(y_cor.iloc[q-1][3]))]
            P = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][4])) & (df_time['x'] <= int(x_cor.iloc[q-1][5])) & (df_time['y'] >= int(y_cor.iloc[q-1][4])) & (df_time['y'] <= int(y_cor.iloc[q-1][5]))]
            
            # QCP contains QAOI, CAOI, and PAOI count of each question
            QCP = np.concatenate((QCP, np.array([Q.shape[0],C.shape[0],P.shape[0]])))
            n = QCP.size # length
            N = 3        # N dimension
            M = n//N
            QCP_reshape = QCP.reshape((M, N))

            # QCP duration
            QCP_duration = np.concatenate((QCP_duration, np.array([sum(Q['duration']),sum(C['duration']),sum(P['duration'])])))
            K = QCP_duration.size//N
            QCP_duration_reshape = QCP_duration.reshape((K, N))

            # combine Q, C , and P as all point data
            QCP_combine = pd.concat([QCP_combine, Q, C, P],axis=0)
            
        # combine count and duration
        QCP_count_duration = np.concatenate((QCP_reshape, QCP_duration_reshape),axis=1)
        
        # output QCP count
        QCP_count_duration_df = pd.DataFrame(QCP_count_duration)
        QCP_count_duration_df.columns = ['QAOI_count', 'CAOI_count', 'PAOI_count','QAOI_duration', 'CAOI_duration', 'PAOI_duration']
        QCP_count_duration_output_path_0 = "/Users/apple/Desktop/202108eyeml/A/AP1_check/QCP_count_duration/A0" + str(p) + ".csv"
        QCP_count_duration_df.to_csv (QCP_count_duration_output_path_0, index = None, header=True)    
        
        # output data used per person
        QCP_combine.sort_values(by=['start_time'], inplace=True)
        QCP_combine_output_path_0 = "/Users/apple/Desktop/202108eyeml/A/AP1_check/A0" + str(p) + ".csv"
        QCP_combine.to_csv (QCP_combine_output_path_0, index = None, header=True) 

    else:
        path_csv = origin_path + "A" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        df_col = df[['CURRENT_FIX_START','CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION']]
        df_col.columns = ['start_time', 'x', 'y', 'duration']

        # form a df with column 'start_time', 'x', 'y', and 'duration', containing each person all data
        QCP_combine = pd.DataFrame(columns=['start_time', 'x', 'y', 'duration']) # empty df
        QCP = []
        QCP_duration = []
        for q in range(1,48):
            if int(resp_array[p-1][q-1]) == 0:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(onset_array[p-1][q-1])+14000)] # Q1,Q2...
            else:
                df_time = df_col[(df_col['start_time']>= int(onset_array[p-1][q-1])) & (df_col['start_time']<= int(resp_array[p-1][q-1]))] # Q1,Q2...
            
            df_time = df_time[(df_time['duration']>= 100)] # duration >= 100

            Q = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][0])) & (df_time['x'] <= int(x_cor.iloc[q-1][1])) & (df_time['y'] >= int(y_cor.iloc[q-1][0])) & (df_time['y'] <= int(y_cor.iloc[q-1][1]))]
            C = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][2])) & (df_time['x'] <= int(x_cor.iloc[q-1][3])) & (df_time['y'] >= int(y_cor.iloc[q-1][2])) & (df_time['y'] <= int(y_cor.iloc[q-1][3]))]
            P = df_time[(df_time['x'] >= int(x_cor.iloc[q-1][4])) & (df_time['x'] <= int(x_cor.iloc[q-1][5])) & (df_time['y'] >= int(y_cor.iloc[q-1][4])) & (df_time['y'] <= int(y_cor.iloc[q-1][5]))]

            # QCP contains QAOI, CAOI, and PAOI count of each question
            QCP = np.concatenate((QCP, np.array([Q.shape[0],C.shape[0],P.shape[0]])))
            n = QCP.size # length
            N = 3        # N dimension
            M = n//N
            QCP_reshape = QCP.reshape((M, N))

            # QCP duration
            QCP_duration = np.concatenate((QCP_duration, np.array([sum(Q['duration']),sum(C['duration']),sum(P['duration'])])))
            K = QCP_duration.size//N
            QCP_duration_reshape = QCP_duration.reshape((K, N))

            # combine Q, C , and P as all point data per person
            QCP_combine = pd.concat([QCP_combine, Q, C, P],axis=0)
            
        # combine count and duration
        QCP_count_duration = np.concatenate((QCP_reshape, QCP_duration_reshape),axis=1)
        
        # output QCP count
        QCP_count_duration_df = pd.DataFrame(QCP_count_duration)
        QCP_count_duration_df.columns = ['QAOI_count', 'CAOI_count', 'PAOI_count','QAOI_duration', 'CAOI_duration', 'PAOI_duration']
        QCP_count_duration_output_path_0 = "/Users/apple/Desktop/202108eyeml/A/AP1_check/QCP_count_duration/A" + str(p) + ".csv"
        QCP_count_duration_df.to_csv (QCP_count_duration_output_path_0, index = None, header=True)  
        
        # output data used per person
        QCP_combine.sort_values(by=['start_time'], inplace=True)
        QCP_combine_output_path = "/Users/apple/Desktop/202108eyeml/A/AP1_check/A" + str(p) + ".csv"
        QCP_combine.to_csv (QCP_combine_output_path, index = None, header=True)

30p*47q*QCP3=4230: 1402

---

# data with answer

In [29]:
# 30人，47題，第一人第一題的QCP各自 count & duration，y：每一題對錯

# answer
answer = pd.read_csv("/Users/apple/Desktop/202108eyeml/A/answer.csv", index_col=None).drop(['0'], axis=1)
QCPcount_path = "/Users/apple/Desktop/202108eyeml/A/AP1_check/QCP_count_duration/"
for p in range(1,31):
    if p <= 9:
        path_csv = QCPcount_path + "A0" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        QCP_count_duration_ans_df = pd.concat([df, pd.DataFrame(answer.iloc[p-1][:]).reset_index(drop=True)], axis = 1)
        QCP_count_duration_ans_df.columns = ['QAOI_count', 'CAOI_count', 'PAOI_count','QAOI_duration', 'CAOI_duration', 'PAOI_duration','answer']
        QCP_count_duration_ans_output_path_0 = "/Users/apple/Desktop/202108eyeml/A/AP1_check/QCP_count_duration_ans/A0" + str(p) + ".csv"
        QCP_count_duration_ans_df.to_csv (QCP_count_duration_ans_output_path_0, index = None, header=True)  
    else:
        path_csv = QCPcount_path + "A" + str(p) + ".csv"
        df = pd.read_csv(path_csv)
        QCP_count_duration_ans_df = pd.concat([df, pd.DataFrame(answer.iloc[p-1][:]).reset_index(drop=True)], axis = 1)
        QCP_count_duration_ans_df.columns = ['QAOI_count', 'CAOI_count', 'PAOI_count','QAOI_duration', 'CAOI_duration', 'PAOI_duration','answer']
        QCP_count_duration_ans_output_path = "/Users/apple/Desktop/202108eyeml/A/AP1_check/QCP_count_duration_ans/A" + str(p) + ".csv"
        QCP_count_duration_ans_df.to_csv (QCP_count_duration_ans_output_path, index = None, header=True)